// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgjRKOZzDAU8UhKVWqAV6UVKzZGZqAPrA',
    appId: '1:861987455422:web:8f5fcc6cd97a2bda9eb9ef',
    messagingSenderId: '861987455422',
    projectId: 'hihi-7aae0',
    authDomain: 'hihi-7aae0.firebaseapp.com',
    storageBucket: 'hihi-7aae0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHiQG_n6eSVsbV6fnOhe93a7xQXuKD7XU',
    appId: '1:861987455422:android:314380ffbe29ec0f9eb9ef',
    messagingSenderId: '861987455422',
    projectId: 'hihi-7aae0',
    storageBucket: 'hihi-7aae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXJHrleUGcTIMdXtiBJlQiEwCbx0x1_Io',
    appId: '1:861987455422:ios:2c3b60a6bad28b099eb9ef',
    messagingSenderId: '861987455422',
    projectId: 'hihi-7aae0',
    storageBucket: 'hihi-7aae0.appspot.com',
    iosClientId: '861987455422-kjdbdoj3ai9n95veb3v5gfnknstr8cbb.apps.googleusercontent.com',
    iosBundleId: 'com.linkusrandc.linkus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXJHrleUGcTIMdXtiBJlQiEwCbx0x1_Io',
    appId: '1:861987455422:ios:6b2678faae38304d9eb9ef',
    messagingSenderId: '861987455422',
    projectId: 'hihi-7aae0',
    storageBucket: 'hihi-7aae0.appspot.com',
    iosClientId: '861987455422-692sskbjil47himlot2au1f4ur5he736.apps.googleusercontent.com',
    iosBundleId: 'com.linkusrandc.linkus.RunnerTests',
  );
}
